export const SET_PLUGINS = "SET_PLUGINS";
export type SET_PLUGINS = typeof SET_PLUGINS;

export const SUBSCRIBE_PLUGIN = "SUBSCRIBE_PLUGIN";
export type SUBSCRIBE_PLUGIN = typeof SUBSCRIBE_PLUGIN;

export const UNSUBSCRIBE_PLUGIN = "UNSUBSCRIBE_PLUGIN";
export type UNSUBSCRIBE_PLUGIN = typeof UNSUBSCRIBE_PLUGIN;
